/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 *
 * AI Market Intelligence — domain types.
 *
 * These interfaces define the contract between the (future) backend analysis
 * pipeline and the UI. The same shapes are produced today by the mock API and
 * tomorrow by the real RSS -> AI -> database pipeline (see api.ts).
 */

export type TrendDirection = 'up' | 'down' | 'stable';
export type Momentum = 'accelerating' | 'steady' | 'cooling';

/** Section 1 — the single featured, AI-generated conclusion of the day. */
export interface DailyInsight {
  id: string;
  title: string;
  summary: string;
  /** Model confidence in the conclusion, 0–100. */
  confidence: number;
  /** How many source articles fed this conclusion. */
  articlesAnalyzed: number;
  /** ISO timestamp of the last analysis run. */
  updatedAt: string;
}

/** Section 2 — a flavor gaining attention across the market. */
export interface FlavorTrend {
  id: string;
  name: string;
  /** Composite attention score, 0–100. */
  trendScore: number;
  /** Week-over-week growth in discussion volume, percentage. */
  growthPct: number;
  /** Model confidence, 0–100. */
  confidence: number;
  direction: TrendDirection;
  /** Food categories / applications where the flavor is trending. */
  categories: string[];
}

/** Section 3 — a product concept rising in popularity. */
export interface ViralProduct {
  id: string;
  name: string;
  /** Popularity index, 0–100. */
  popularity: number;
  /** Growth rate over the analysis window, percentage. */
  growthRate: number;
  category: string;
  momentum: Momentum;
}

/** Section 4 — an AI-generated business opportunity. */
export interface Opportunity {
  id: string;
  title: string;
  description: string;
  /** Attractiveness of the opportunity, 0–100. */
  opportunityScore: number;
  /** Model confidence, 0–100. */
  confidence: number;
  segment: string;
  suggestion: string;
}

/** Section 5 — a source article used for transparency. */
export interface SourceArticle {
  id: string;
  title: string;
  source: string;
  /** ISO publish date. */
  publishedAt: string;
  url?: string;
}

/** The full daily snapshot stored in the database and served to the UI. */
export interface MarketIntelligenceSnapshot {
  /** ISO timestamp the snapshot was generated by the pipeline. */
  generatedAt: string;
  /** Analysis look-back window in days. */
  windowDays: number;
  insight: DailyInsight;
  flavors: FlavorTrend[];
  products: ViralProduct[];
  opportunities: Opportunity[];
  sources: SourceArticle[];
}
